### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Flynsarmy** [gtibo/VFX-sketchbook#1]
Any chance you could add a license to this repo? Software is copyrighted by default so as it stands noone can make use of your incredible work!

**Comment by gtibo** [comment]
Hey :) I was thinking putting the [cc-by-40](https://choosealicense.com/licenses/cc-by-4.0/) license in the repo, but I don't know if it's the most adequate, I need to take time to look around, but I'll add one when I have the time.

**Comment by chunribu** [comment]
@gtibo Thank you for your sharing, really great work!
