### ISSUE TITLE
Shader invisible from certain angles with certain shapes

### ISSUE THREAD

**Issue by RazzNon** [gtibo/VFX-sketchbook#2]
Hello

I'm curious if there's a way to adjust the shader as it turns invisible from certain angles.  The force field shader for example works great for complex shapes or rounded shapes.  When I use it on a simpler object with large flat surfaces it turns invisible when looking at those surfaces head on.

Looks good at an angle:
![image](https://github.com/gtibo/VFX-sketchbook/assets/153390775/d6eb20fc-ce12-4c90-be49-d5b4f85f6001)

Flat surface turns invisible when rotating camera.
![image](https://github.com/gtibo/VFX-sketchbook/assets/153390775/e82c75ff-7e39-45e9-8440-08b74191b591)

**Comment by gtibo** [comment]
This is related to the Fresnel, so this behavior is expected, perhaps adjusting the amount of Fresnel could help.
Another possibility is to set a minimum alpha relative to the camera orientation, so that when the mesh is viewed from the front, it's always visible at a minimum.

**Comment by RazzNon** [comment]
Yes, that fixed the problem.  Thank you!  I clamped the alpha value as well as lowering the Fresnel amount.  I also had a question regarding your hologram effect but I will submit that on your shader playground repo.
