### ISSUE TITLE
Windows defender find trojan in the downloaded zip file

### ISSUE THREAD

**Issue by nagasawamaki** [gtibo/VFX-sketchbook#4]
Windows defender find trojan in the downloaded zip file:

![圖片](https://github.com/gtibo/VFX-sketchbook-Godot-4.x/assets/24987226/8296ddb5-25e9-415b-85d2-24b2965ab646)

I am using Windows 10

Any hints?

Thanks

**Comment by gtibo** [comment]
I don't know enough about Windows to answer precisely, but there are no executable files in this repository and all the code is Gdscript which is specific to the Godot editor and only runs inside it. It looks very much like a false alarm.

**Comment by Xananax** [comment]
It seems to be a common false positive. There is some info about it here: 

- https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/Trojan.BAT.DOWNLOADER.B/
- https://gridinsoft.com/blogs/trojanwin32-wacatac/

It technically could be done through GDScript, but it'd need either @gtibo to write that code explicitly, or someone to do a hostile commit (a commit with hidden malicious code).

The repo does not contain viruses at the moment.
